import type { Metadata } from "next";
import { Geist, Geist_Mono, Grand_Hotel, Cormorant, ABeeZee, Bebas_Neue, Oswald } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const grandHotel = Grand_Hotel({
  weight:"400",
  variable:"--font-grand-hotel",
  subsets:["latin"],

})

const cormorant = Cormorant({
  weight:"400",
  variable:"--font-cormorant",
  subsets:["latin"],

})

const abeezee = ABeeZee({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-abeezee",
  display: "swap",
})

const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bebas",
})

const oswald = Oswald({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-oswald",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${grandHotel.variable} ${cormorant.variable} ${abeezee.variable} ${bebas.variable} ${oswald.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
